name: Terraform CI/CD

on:
  pull_request:
    branches:
      - 'main'
      
  workflow_dispatch:

jobs:
  run-echo-1:
    runs-on: ubuntu-latest
    steps:
      - name: Run echo 1
        run: echo "1"
