name: Merge validation

on:
  push:
    branches:
      - 'edit'
    paths:
      - 'Assignment2/**'

jobs:
  validate-terraform:
    name: 'Validate Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Specify the version you want to use

      - name: Terraform init
        run: terraform init
        working-directory: ./Assignment2

      - name: Terraform validate
        run: terraform validate
        working-directory: ./Assignment2

  security-check:
    name: 'Security Check'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ./Assignment2
          github_token: ${{ secrets.GITHUB_TOKEN }}

  tflint-check:
    name: 'TFLint Check'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4.0.0
        with:
          tflint_version: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tflint_wrapper: false

      - name: Run TFLint
        run: |
          cd ./Assignment2
          tflint

  format-check:
    name: 'Terraform Format Check'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Specify the version you want to use

      - name: Run 'terraform fmt'
        run: |
          cd ./Assignment2 
          terraform fmt -check -diff
