name: Terraform Linter

on:
  workflow_run:
    workflows: ["Validate Infrastructure"]
    types:
      - completed
  workflow_dispatch:

jobs:
  tflint:
    name: 'TFLint Check'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4.0.0
        with:
          tflint_version: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tflint_wrapper: false

      - name: Run TFLint
        run: |
          cd ./Assignment2
          tflint
