name: Terraform Linter

on:
  # Triggers the workflow on push or pull request events
 push:
    branches:
      - 'Edit'
    paths:
      - 'Assignment2/**'

jobs:
  tflint:
    name: 'TFLint Check'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4.0.0
        with:
          tflint_version: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tflint_wrapper: false

      - name: Run TFLint
        run: |
          cd ./Assignment2
          tflint
