name: Terraform Security Check

on:
  workflow_run:
    workflows: ["Validate Infrastructure"]
    types:
      - completed
  workflow_dispatch:

jobs:
  terraform:
    name: 'Security Check'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./Assignment2
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@master
      - name: Set TFSEC_CUSTOM_RULES
        run: echo "TFSEC_CUSTOM_RULES={\"azure-compute-disable-password-authentication\":{\"bypass\":true}}" >> $GITHUB_ENV
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ env.WORKING_DIR }}
          github_token: ${{ env.GITHUB_TOKEN }}
